const mongoose = require("mongoose");

const schema = mongoose.Schema(
  {
    user_id: { type: String},
    code: { type: String},
    was_autogenerated:{type: Boolean, default: false},
    generated_by:{type: String},
    isActive: {type: Boolean},
    expires_at: {type: Date},
    code_age:{type: String}
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
  }
);

module.exports = mongoose.model("InviteCode", schema);
